### ISSUE TITLE
Lampainit.js

### ISSUE THREAD

**Issue by dshkoda32** [immisterio/Lampac#1]
Подскажите, хотел в lampainit добавить плагин на радио вместо клубнички и адрес торрсервера, но при запуске лампы все данные ставятся по умолчанию. Можно ли как то добавлять свои настройки?

**Comment by immisterio** [comment]
Инициализация происходит при первом открытии, после инициализации изменения в скрипте не учитываются. 

Для отключения проверки можно закомментировать 
Lampa.Storage.set('lampac_initiale','true');

**Comment by dshkoda32** [comment]
А как сделать , чтобы при загрузке плагина lampainit.js на другом адресе лампы, он запускался при каждой загрузке приложения, другими словами чтобы было также как я запускаю lampac и настройки с изменениями подгружались постоянно из этого плагина , а не только при первой загрузке.
