### ISSUE TITLE
Загрузка процессора 10% lampac.dll

### ISSUE THREAD

**Issue by stalkerdm** [immisterio/Lampac#14]
Установил lampac на Ubuntu 22.04, lampac.dll постоянно загружает процессор на 10-15%, в простое. Иногда до 70%!!!

**Comment by immisterio** [comment]
В module/manifest.json отключите JacRed

**Comment by stalkerdm** [comment]
Спсибо! Но тогда парсер не будет работать, а мне он нужен, пусть уж 10% процессора ест.

**Comment by immisterio** [comment]
Уменьшил интервал синхронизации и убрал лишние проверки в 21.03.2023 , нагрузка на cpu останется, но уже в промежутке 1 раз в час на 5-10 минут.
