### ISSUE TITLE
lam62

### ISSUE THREAD

**Issue by Arkady91** [immisterio/Lampac#15]
Как обновить Lampac на ubuntu?

**Comment by immisterio** [comment]
Перезаписать файлы с update.zip

**Comment by JoyZzzzz** [comment]
А обновления разве автоматом не ставятся по крону при установке скриптом?

**Comment by Arkady91** [comment]
Можете ещё подсказать как установить tor?
Я так полагаю, он нужен для того что бы все балансеры работали?
