### ISSUE TITLE
Не работают сервисы..

### ISSUE THREAD

**Issue by Newbaatt** [immisterio/Lampac#2]
Добрый день! Установил на Debian 11 в локалке с помощью скрипта. Проверил, служба стартанула, ошибок не дает. Но ни один сервис на порту 9118 не пашет. IPTABLES обнулял, не помогло...Насколько я понял, он должен хотя бы доступ из браузера дать, например по http://IP:9118/sisi.js, но нет страницы...не подскажете, как решить проблему?

**Comment by immisterio** [comment]
Проверьте в 127.0.0.1

**Comment by Newbaatt** [comment]
Попробовал двумя разными браузерами (elinks и links2), не работает...
![Новый рисунок_2](https://user-images.githubusercontent.com/99191388/201579655-9ac49b84-0f7e-4f4d-bdf3-4234f51ba632.jpg)
![Новый рисунок (1)](https://user-images.githubusercontent.com/99191388/201579656-a8346881-25d7-4f4a-9ebd-a228fcba20d2.jpg)

**Comment by immisterio** [comment]
service lampac status

**Comment by Newbaatt** [comment]
![Новый рисунок](https://user-images.githubusercontent.com/99191388/201657649-20793955-cebb-425d-b932-47b0c8e1737f.png)
Я немного подправил скрипт и установил на в $home, а в /opt. Но после того, как не заработало, я пробовал и в $home устанавливать, результат тот же...
а может, службу надо не от рута запускать и в этом все дело?

**Comment by immisterio** [comment]
попробуйте curls -s "http://127.0.0.1:9118/online.js"

**Comment by Newbaatt** [comment]
команды curl -s "http://127.0.0.1:9118/online.js" и curl -s "http://127.0.0.1:9118/sisi.js" терминал проглотил без ошибок. Но при попытке открыть сервисы локальным браузером - то же самое, ошибка.

**Comment by immisterio** [comment]
тут уже проблема в браузере

**Comment by Newbaatt** [comment]
Попробовал, та же история. Установил ради эксперимента на одноплатник (там распбиан на основе дебиан 9) - там все заработало с полпинка. Вообще у меня ощущение, что на машине, на которой не работает - поломан дотнет, т.к. я раньше с ним игрался много. Не подскажете, как проверить, что там может быть неисправно и как починить?

**Comment by immisterio** [comment]
Можно попробовать переустановить dotnet, так даже хз
