### ISSUE TITLE
Как отслеживать версию lampac?

### ISSUE THREAD

**Issue by A-Spilberg** [immisterio/Lampac#21]
Добавьте плз что-то типа version файла чтобы можно было понять какой именно билд скачан. Т.к. довольно проблематично отследить установлен ли нужный релиз или нет. Спасибо.

**Comment by immisterio** [comment]
Добавлю в следящем обновлении

**Comment by immisterio** [comment]
IP:9118/version

**Comment by butaford** [comment]
Есть ли смысл при `"accsdb":true` чтобы возвращался ответ версии, иначе возвращается `"denyMesage":`
