### ISSUE TITLE
Падает lampac в linux

### ISSUE THREAD

**Issue by isergiograys** [immisterio/Lampac#23]
Запускаю dotnet Lampac.dll. Все стартует нормально, но как только пытаюсь зайти с самого ноутбука, где установлен lampac, или с любого другого устройства по ip:9118, то сервис падает с ошибкой на фото. Система Ubuntu 22.04. На Винде на том же ноуте все нормально работает. Но нужно оставить именно на линукс. Что это может быть и куда копать?
<a href="https://ibb.co/gDrYwVh"><img src="https://i.ibb.co/GVdmkTN/IMG-20230814-154108.jpg" alt="IMG-20230814-154108" border="0"></a><br /><a target='_blank' href='https://ru.imgbb.com/'>радикал ру</a><br />

**Comment by butaford** [comment]
Lampac "прибит" к пути `/home/lampac` и запускать надо оттуда.

**Comment by isergiograys** [comment]
> Lampac "прибит" к пути `/home/lampac` и запускать надо оттуда. Физически вы можете положить куда угодно и сделать симлинк в папку `/home/lampac/` и запускать оттуда же

Самое интересное, что после обновления системы все заработало. Хотя ничего не менял больше. Единственное, чтобы заработал сервис лампака в фоне, поменял dotnet из /user/ на тот что в /bin
