### ISSUE TITLE
После создания init.conf lampac не запускается

### ISSUE THREAD

**Issue by stalkerdm** [immisterio/Lampac#25]
Создал init.conf, но lampac не запускается, если удалить файл, то запускается.

{
"accsdb": {
    "enable": true,
	"whitepattern": "^/over/",
    "maxiptohour": 10,
	"cubMesage": "Войдите в аккаунт",
	"denyMesage": "Добавьте {account_email} в init.conf",
	"accounts": [
	  "mail@mail.com"
	]
  }
}

**Comment by JoyZzzzz** [comment]
надо формат пользователей поменять на  

"accounts": {
    "1mail.ru": "2035-10-17T00:00:00",
    "2mail.ru": "2035-10-17T00:00:00",
  }

 пример
"accsdb": {
    "enable": true,
  "whitepattern": "^/over/",
    "maxiptohour": 10,
  "cubMesage": "Войдите в аккаунт",
  "denyMesage": "Добавьте {account_email} в init.conf",
  "accounts": {
    "megachel@gmail.com": "2040-10-17T00:00:00",
    "ehechel@gmail.com": "2040-10-17T00:00:00",
  }
  },

**Comment by stalkerdm** [comment]
Спасибо, все заработало!

**Comment by immisterio** [comment]
> Не подскажите как сменить путь к папке dlna?

Добавлю в релизе, а так можно через символические ссылки ln -s
