### ISSUE TITLE
Клубничка

### ISSUE THREAD

**Issue by krilzov** [immisterio/Lampac#26]
Скажите пожалуйста как полностью отключить (удалить) плагин - Клубничка, чтобы после сброса кэша или настроек плагина не было

**Comment by bonuzzz** [comment]
расширения -- клубничка -- удалить
появится ли потом при обновлении не подскажу

**Comment by immisterio** [comment]
В файле module/manifest.json для SISI.dll поставить enable: false

**Comment by immisterio** [comment]
Либо в init.conf отключить добавление плагина при первом открытии лампы, но оставить возможность добавить плагин вручную http://ip:9118/sisi.js для тех кому нужно

```
 "LampaWeb": {
	"initPlugins": {
	  "sisi": false
	}
  },
```

**Comment by krilzov** [comment]
> В файле module/manifest.json для SISI.dll поставить enable: false , отключит как сам плагин, так и api для него

Спасибо большое, этот метод помог!
