### ISSUE TITLE
Плагин online.js - Ошибка сервер не отвечает на запрос

### ISSUE THREAD

**Issue by krilzov** [immisterio/Lampac#28]
Приветствую друзья! При использовании lampa (установлена на ubuntu) через реверс прокси (с использованием сертификата по https без указания порта 9118) плагин online.js выдаёт: Ошибка сервер не отвечает на запрос. Остальные плагины работают исправно. По локальному ip:9118 всё работает идеально. Есть решение проблемы?
p.s. при замене плагина online.js на плагин (онлайн мод) - всё работает.

**Comment by immisterio** [comment]
смотрите что пишет консоль браузер, так же в nginx нужно указать все заголовки 

```
location /proxy/ {
      proxy_pass  http://127.0.0.1:9118;
	  
	  proxy_buffering       off;
	  proxy_buffer_size     4k;
      proxy_http_version    1.1;
      proxy_redirect 	    off;

      proxy_set_header 	Host 			  $host;
      proxy_set_header	X-Real-IP 		  $remote_addr;
      proxy_set_header	X-Forwarded-For	  $proxy_add_x_forwarded_for;
      proxy_set_header	X-Forwarded-Proto $scheme;
	  proxy_set_header	Connection        "";

	  proxy_headers_hash_max_size 512;
	  proxy_headers_hash_bucket_size 128;
	  
	  proxy_connect_timeout	15;
	  proxy_send_timeout	20;
	  proxy_read_timeout	20;
   }
   
   location / {
      proxy_pass  http://127.0.0.1:9118;
	  
      proxy_http_version       1.1;
      proxy_redirect           off;

      proxy_set_header	Host 			  $host;
      proxy_set_header	X-Real-IP 		  $remote_addr;
      proxy_set_header	X-Forwarded-For	  $proxy_add_x_forwarded_for;
      proxy_set_header	X-Forwarded-Proto $scheme;

      client_max_body_size 	  10m;
      client_body_buffer_size 128k;
      proxy_buffers			  32 4k;
	  
      proxy_connect_timeout 	20;
      proxy_send_timeout 		40;
      proxy_read_timeout 		40;

      proxy_headers_hash_max_size 512;
      proxy_headers_hash_bucket_size 128;
   }
```

**Comment by krilzov** [comment]
> смотрите что пишет консоль браузера, так же в nginx нужно указать все заголовки
> 
> ```
> location /proxy/ {
>       proxy_pass  http://127.0.0.1:9118;
> 	  
>       proxy_buffering       off;
>       proxy_buffer_size     4k;
>       proxy_http_version    1.1;
>       proxy_redirect 	    off;
> 
>       proxy_set_header 	Host		  $host;
>       proxy_set_header	X-Real-IP	  $remote_addr;
>       proxy_set_header	X-Forwarded-For	  $proxy_add_x_forwarded_for;
>       proxy_set_header	X-Forwarded-Proto $scheme;
>       proxy_set_header	Connection        "";
> 
>       proxy_headers_hash_max_size 512;
>       proxy_headers_hash_bucket_size 128;
> 	  
>       proxy_connect_timeout	15;
>       proxy_send_timeout	20;
>       proxy_read_timeout	20;
>    }
>    
>    location / {
>       proxy_pass  http://127.0.0.1:9118;
> 	  
>       proxy_http_version       1.1;
>       proxy_redirect           off;
> 
>       proxy_set_header	Host		  $host;
>       proxy_set_header	X-Real-IP	  $remote_addr;
>       proxy_set_header	X-Forwarded-For	  $proxy_add_x_forwarded_for;
>       proxy_set_header	X-Forwarded-Proto $scheme;
> 
>       client_max_body_size  10m;
>       client_body_buffer_size 128k;
>       proxy_buffers	  32 4k;
> 	  
>       proxy_connect_timeout 20;
>       proxy_send_timeout 40;
>       proxy_read_timeout 40;
> 
>       proxy_headers_hash_max_size 512;
>       proxy_headers_hash_bucket_size 128;
>    }
> ```

≈

**Comment by krilzov** [comment]
К сожалению так и не удалось победить работу плагина online.js (ресурс: http://krilzov.line.pm), в nginx не силён особо, заголовки выше прописал... теперь лампа выдаёт - не удалось найти онлайн для фильма
