### ISSUE TITLE
Tor

### ISSUE THREAD

**Issue by dshkoda32** [immisterio/Lampac#4]
Перестало на последних обновлениях искать торренты через сеть Tor.

**Comment by immisterio** [comment]
https://nnmclub.to/forum/viewtopic.php?t=958541&start=60

**Comment by dshkoda32** [comment]
Дело наверное даже не в nnm, попробовал рутор и рутрекер через .onion , также результаты не выводит

**Comment by immisterio** [comment]
Проблема не связана lampac

**Comment by dshkoda32** [comment]
Поставил tor на тот же сервер что и lampac, тогда заработало
