### ISSUE TITLE
Джерела

### ISSUE THREAD

**Issue by Syvyj** [immisterio/Lampac#42]
Чи можна якось зробити, щоб серед джерел були тільки українські сайти?

**Comment by isergiograys** [comment]
Можна. Для цього у init.conf на усіх непотрібних джерелах має бути false. Наприклад: 
{
    "rezka": {
     "enable": false
 }
}
І так далі.

**Comment by Syvyj** [comment]
> Можна. Для цього у init.conf на усіх непотрібних джерелах має бути false. Наприклад: { "rezka": { "enable": false } } І так далі.

дякую, а де цей файл знаходиться, якщо я використовую Android TV версію?

**Comment by isergiograys** [comment]
Його треба створити в корені теки lampac. За замовчуванням його немає. Сама тека знаходиться на тому пристрої, де встановлено lampac
