### ISSUE TITLE
Bitru

### ISSUE THREAD

**Issue by dshkoda32** [immisterio/Lampac#5]
Трекер bitru в jacweb не выводит результаты, хотя в лампе находит.

**Comment by immisterio** [comment]
https://github.com/immisterio/Lampac/commit/a727f33cc4a4a98b3413fea161bb87e84b50929b

**Comment by dshkoda32** [comment]
С megapeer такая же проблема

**Comment by immisterio** [comment]
находит

**Comment by dshkoda32** [comment]
![IMG_20221208_210006](https://user-images.githubusercontent.com/103311492/206532762-58008ce2-baa2-4329-a08d-4c68d3b26e17.jpg)
![IMG_20221208_205814](https://user-images.githubusercontent.com/103311492/206532779-5026247d-24ad-4acd-9c25-77077f9fd224.jpg)

**Comment by immisterio** [comment]
Ищите проблему между провайдером и megapeer
