### ISSUE TITLE
jackett удаленный доступ

### ISSUE THREAD

**Issue by alexunderboots** [immisterio/Lampac#6]
Добрый день. Как получить доступ к жакету из локального qbittorrenta, Lampac установлен на vps.
получаю ошибку
Jackett: connection error! Right-click this row and select 'Open description page' to open help. Configuration file: 'C:\Users\user\AppData\Local\qBittorrent\nova3\engines\jackett.json'

**Comment by immisterio** [comment]
Это обрезанная версия под лампу и нум
